// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.antu.nmea.protobuf;

public final class GgaSentence {
  private GgaSentence() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SentenceOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string UTCtime = 1;
    boolean hasUTCtime();
    String getUTCtime();
    
    // required double latitude = 2;
    boolean hasLatitude();
    double getLatitude();
    
    // required string earth = 3;
    boolean hasEarth();
    String getEarth();
    
    // required double longitude = 4;
    boolean hasLongitude();
    double getLongitude();
    
    // required string earth2 = 5;
    boolean hasEarth2();
    String getEarth2();
  }
  public static final class Sentence extends
      com.google.protobuf.GeneratedMessage
      implements SentenceOrBuilder {
    // Use Sentence.newBuilder() to construct.
    private Sentence(Builder builder) {
      super(builder);
    }
    private Sentence(boolean noInit) {}
    
    private static final Sentence defaultInstance;
    public static Sentence getDefaultInstance() {
      return defaultInstance;
    }
    
    public Sentence getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.antu.nmea.protobuf.GgaSentence.internal_static_Sentence_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.antu.nmea.protobuf.GgaSentence.internal_static_Sentence_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string UTCtime = 1;
    public static final int UTCTIME_FIELD_NUMBER = 1;
    private java.lang.Object uTCtime_;
    public boolean hasUTCtime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUTCtime() {
      java.lang.Object ref = uTCtime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uTCtime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUTCtimeBytes() {
      java.lang.Object ref = uTCtime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uTCtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private double latitude_;
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLatitude() {
      return latitude_;
    }
    
    // required string earth = 3;
    public static final int EARTH_FIELD_NUMBER = 3;
    private java.lang.Object earth_;
    public boolean hasEarth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getEarth() {
      java.lang.Object ref = earth_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          earth_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEarthBytes() {
      java.lang.Object ref = earth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        earth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double longitude = 4;
    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_;
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getLongitude() {
      return longitude_;
    }
    
    // required string earth2 = 5;
    public static final int EARTH2_FIELD_NUMBER = 5;
    private java.lang.Object earth2_;
    public boolean hasEarth2() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getEarth2() {
      java.lang.Object ref = earth2_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          earth2_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEarth2Bytes() {
      java.lang.Object ref = earth2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        earth2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      uTCtime_ = "";
      latitude_ = 0D;
      earth_ = "";
      longitude_ = 0D;
      earth2_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUTCtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEarth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEarth2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUTCtimeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getEarthBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getEarth2Bytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUTCtimeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, latitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getEarthBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getEarth2Bytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.antu.nmea.protobuf.GgaSentence.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.antu.nmea.protobuf.GgaSentence.Sentence prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.antu.nmea.protobuf.GgaSentence.SentenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.antu.nmea.protobuf.GgaSentence.internal_static_Sentence_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.antu.nmea.protobuf.GgaSentence.internal_static_Sentence_fieldAccessorTable;
      }
      
      // Construct using com.antu.nmea.protobuf.GgaSentence.Sentence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uTCtime_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        earth_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        earth2_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.antu.nmea.protobuf.GgaSentence.Sentence.getDescriptor();
      }
      
      public com.antu.nmea.protobuf.GgaSentence.Sentence getDefaultInstanceForType() {
        return com.antu.nmea.protobuf.GgaSentence.Sentence.getDefaultInstance();
      }
      
      public com.antu.nmea.protobuf.GgaSentence.Sentence build() {
        com.antu.nmea.protobuf.GgaSentence.Sentence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.antu.nmea.protobuf.GgaSentence.Sentence buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.antu.nmea.protobuf.GgaSentence.Sentence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.antu.nmea.protobuf.GgaSentence.Sentence buildPartial() {
        com.antu.nmea.protobuf.GgaSentence.Sentence result = new com.antu.nmea.protobuf.GgaSentence.Sentence(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uTCtime_ = uTCtime_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.earth_ = earth_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.earth2_ = earth2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.antu.nmea.protobuf.GgaSentence.Sentence) {
          return mergeFrom((com.antu.nmea.protobuf.GgaSentence.Sentence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.antu.nmea.protobuf.GgaSentence.Sentence other) {
        if (other == com.antu.nmea.protobuf.GgaSentence.Sentence.getDefaultInstance()) return this;
        if (other.hasUTCtime()) {
          setUTCtime(other.getUTCtime());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasEarth()) {
          setEarth(other.getEarth());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasEarth2()) {
          setEarth2(other.getEarth2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUTCtime()) {
          
          return false;
        }
        if (!hasLatitude()) {
          
          return false;
        }
        if (!hasEarth()) {
          
          return false;
        }
        if (!hasLongitude()) {
          
          return false;
        }
        if (!hasEarth2()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uTCtime_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              latitude_ = input.readDouble();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              earth_ = input.readBytes();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              longitude_ = input.readDouble();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              earth2_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string UTCtime = 1;
      private java.lang.Object uTCtime_ = "";
      public boolean hasUTCtime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUTCtime() {
        java.lang.Object ref = uTCtime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uTCtime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUTCtime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uTCtime_ = value;
        onChanged();
        return this;
      }
      public Builder clearUTCtime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uTCtime_ = getDefaultInstance().getUTCtime();
        onChanged();
        return this;
      }
      void setUTCtime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uTCtime_ = value;
        onChanged();
      }
      
      // required double latitude = 2;
      private double latitude_ ;
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLatitude() {
        return latitude_;
      }
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000002;
        latitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        latitude_ = 0D;
        onChanged();
        return this;
      }
      
      // required string earth = 3;
      private java.lang.Object earth_ = "";
      public boolean hasEarth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getEarth() {
        java.lang.Object ref = earth_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          earth_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEarth(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        earth_ = value;
        onChanged();
        return this;
      }
      public Builder clearEarth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        earth_ = getDefaultInstance().getEarth();
        onChanged();
        return this;
      }
      void setEarth(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        earth_ = value;
        onChanged();
      }
      
      // required double longitude = 4;
      private double longitude_ ;
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getLongitude() {
        return longitude_;
      }
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000008;
        longitude_ = value;
        onChanged();
        return this;
      }
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      
      // required string earth2 = 5;
      private java.lang.Object earth2_ = "";
      public boolean hasEarth2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getEarth2() {
        java.lang.Object ref = earth2_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          earth2_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEarth2(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        earth2_ = value;
        onChanged();
        return this;
      }
      public Builder clearEarth2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        earth2_ = getDefaultInstance().getEarth2();
        onChanged();
        return this;
      }
      void setEarth2(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        earth2_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:Sentence)
    }
    
    static {
      defaultInstance = new Sentence(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Sentence)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Sentence_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sentence_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"_\n\010Sentence\022\017\n\007UTCtime\030\001 \002(" +
      "\t\022\020\n\010latitude\030\002 \002(\001\022\r\n\005earth\030\003 \002(\t\022\021\n\tlo" +
      "ngitude\030\004 \002(\001\022\016\n\006earth2\030\005 \002(\tB%\n\026com.ant" +
      "u.nmea.protobufB\013GgaSentence"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Sentence_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Sentence_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Sentence_descriptor,
              new java.lang.String[] { "UTCtime", "Latitude", "Earth", "Longitude", "Earth2", },
              com.antu.nmea.protobuf.GgaSentence.Sentence.class,
              com.antu.nmea.protobuf.GgaSentence.Sentence.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
